### PR TITLE
Fix for `from_edge` and rings

### LINKED ISSUE #30: `from_edge` and rings
In our implementation of `from_edge`, we allow to repeat segments. Thus, in `merge_lines` we currently skip checking whether a segment has been used. This is a problem for loops and rings, because the keep circling and the while loop never breaks. We should instead forbid repeating segments within a stroke but still allow repeated segments across strokes.

### PR DESCRIPTION
**Pull request by fnattino**
Closes #30

### CODE REVIEW

File: R/stroke.R [hunk 1]
```diff
@@ -141,18 +141,18 @@ best_link <- function(nodes, segments, links, edge_ids, flow_mode,
     return(linked_nodes)
   }
 
+  get_link_on_same_edge <- function(linked_segs, current_segment) {
```
Comment (fnattino) [inline R/stroke.R:144]: After some more thoughts on this, I  think this best suit being outside `find_best_link`, being on the same level as `get_linked_segments` and `get_linked_nodes`. Also, the variable we want to access without being a "real" input of the function is `edge_ids`, which is the vector storing all the original edge IDs for the segments.

File: R/stroke.R [hunk 2]
```diff
@@ -240,6 +240,70 @@ cross_check_links <- function(best_links) {
   return(links)
 }
 
+#' @noRd
+to_linestring <- function(stroke, segments, nodes) {
```
Comment (fnattino) [inline R/stroke.R:244]: Simplifying `traverse_segments` and the main body of `merge_lines` made this function more complex, but I guess this is how it has to be. 

Also, I had to take this and `traverse_segments` back out from `merge_lines` because the linter would otherwise still raise issues with `merge_lines` still having too large cyclomatic complexity. But I have double-checked and R should pass variables by reference (until these are not modified), so this should not give rise to any unexpected double memory usaget..

File: tests/testthat/test-stroke.R [hunk 3]
```diff
@@ -24,15 +24,14 @@ test_that("a stroke is found in a very simple network", {
...
-
   expected <- sf::st_sfc(sf::st_linestring(c(p1, p2, p3)), l3)
   actual <- stroke(sfc)
   expect_setequal(actual, expected)
 })
 
 test_that("a ring is recognized as a stroke", {
   sfc <- sf::st_sfc(l2, l4, l6, l7)
-  expected <- sf::st_sfc(sf::st_linestring(c(p3, p6, p5, p2, p3)))
+  expected <- sf::st_sfc(sf::st_linestring(c(p2, p3, p6, p5, p2)))
```
Comment (fnattino) [inline tests/testthat/test-stroke.R:34]: Having slightly modified `merge_lines`, created a small difference on how strokes are constructed, so the ring now starts at a different position

File: R/stroke.R [hunk 4]
```diff
@@ -254,66 +318,30 @@ merge_lines <- function(nodes, segments, links, edge_ids,
...
+    # revert the stroke to traverse backwards from the start node of the
+    # current segment, then revert it back to the original direction
+    node  <- segments[iseg, "start"]
+    link <- links[iseg, "start"]
+    stroke <- rev(stroke)
+    stroke <- traverse_segments(stroke, node, link, can_reuse_segments,
+                                segments, links, is_segment_used)
+    stroke <- rev(stroke)
+
+    is_segment_used[stroke] <- TRUE
```
Comment (cforgaci) [inline R/stroke.R:342]:
```suggestion
    # keep track of edge ids of strokes and add current stroke to strokes 
    is_segment_used[stroke] <- TRUE
```

**Review by cforgaci — APPROVED** [review]
@fnattino, it looks great! I added a small suggestion. Also we may want to reorder function calls to make sure that the calling function always appears first, so:

- `check_resiprocal()` after `cross_check_links()`
- `to_linestring()` and `traverse_segments()` after `merge_lines()`
